// ============================================================
//  Pattern Matrix Generator using NTL
//  
//  Reads:  prime p  and  seed pattern matrix  from the user
//  Writes: all possible pattern matrices to pattern_output.txt
//
//  A pattern matrix is an n×n matrix where:
//    • Every element is in the range [1, p-1]
//    • All elements are globally unique across the matrix
//    • Every row sums to p-1
//
//  New pattern matrices are generated by three shuffle types:
//    1. Row shuffling     – all permutations of rows
//    2. Column shuffling  – all permutations of columns
//    3. Element shuffling – all per-row element permutations
//
//  Each generated matrix is reduced mod p (every element % p) before saving.
//
//  Compile: g++ -o pattern_matrix pattern_matrix.cpp -lntl -lgmp -lm
//  Run:     ./pattern_matrix
// ============================================================

#include <iostream>
#include <fstream>
#include <vector>
#include <set>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <functional>

using namespace std;

typedef vector<vector<long>> Matrix;
typedef vector<long>         Row;

// ─────────────────────────────────────────────────────────────
// Check if n is prime (trial division)
// ─────────────────────────────────────────────────────────────
bool isPrime(long n) {
    if (n < 2) return false;
    if (n == 2) return true;
    if (n % 2 == 0) return false;
    for (long i = 3; i <= (long)sqrt((double)n); i += 2)
        if (n % i == 0) return false;
    return true;
}

// ─────────────────────────────────────────────────────────────
// Flatten matrix → vector  (used as unique key in seen-set)
// ─────────────────────────────────────────────────────────────
vector<long> flatten(const Matrix& M) {
    vector<long> flat;
    for (const auto& row : M)
        for (long v : row)
            flat.push_back(v);
    return flat;
}

// ─────────────────────────────────────────────────────────────
// Write a matrix to any ostream
// ─────────────────────────────────────────────────────────────
void writeMatrix(ostream& out, const Matrix& M) {
    for (const auto& row : M) {
        out << "[ ";
        for (long v : row) out << v << "\t";
        out << "]\n";
    }
    out << "\n";
}

// ─────────────────────────────────────────────────────────────
// Apply mod p to every element of a matrix and return result.
// Uses ((v % p) + p) % p to safely handle any value.
// ─────────────────────────────────────────────────────────────
Matrix modMatrix(const Matrix& M, long p) {
    Matrix result = M;
    for (auto& row : result)
        for (long& v : row)
            v = ((v % p) + p) % p;
    return result;
}


// ─────────────────────────────────────────────────────────────
// Validate that M is a valid pattern matrix for prime p:
//   • Every element is in [1, p-1]
//   • All elements are globally unique
//   • Every row sums to p-1
// ─────────────────────────────────────────────────────────────
bool isPatternMatrix(const Matrix& M, long p) {
    set<long> globalSeen;
    int n = (int)M.size();
    for (int i = 0; i < n; ++i) {
        long rowSum = 0;
        for (long v : M[i]) {
            if (v <= 0 || v >= p) {
                cerr << "  [Error] Element " << v << " in row " << i + 1
                     << " is out of range. Must be in [1, " << p - 1 << "].\n";
                return false;
            }
            if (globalSeen.count(v)) {
                cerr << "  [Error] Element " << v
                     << " appears more than once in the matrix.\n";
                return false;
            }
            globalSeen.insert(v);
            rowSum += v;
        }
        if (rowSum != p - 1) {
            cerr << "  [Error] Row " << i + 1 << " sums to " << rowSum
                 << " but must equal p-1 = " << p - 1 << ".\n";
            return false;
        }
    }
    return true;
}

// ─────────────────────────────────────────────────────────────
// 1. Row shuffling – all permutations of rows
// ─────────────────────────────────────────────────────────────
void generateRowShuffles(const Matrix& M,
                         set<vector<long>>& seen,
                         vector<Matrix>& results) {
    int n = (int)M.size();
    vector<int> idx(n);
    iota(idx.begin(), idx.end(), 0);

    do {
        Matrix candidate(n);
        for (int i = 0; i < n; ++i)
            candidate[i] = M[idx[i]];

        auto key = flatten(candidate);
        if (!seen.count(key)) {
            seen.insert(key);
            results.push_back(candidate);
        }
    } while (next_permutation(idx.begin(), idx.end()));
}

// ─────────────────────────────────────────────────────────────
// 2. Column shuffling – all permutations of columns
// ─────────────────────────────────────────────────────────────
void generateColShuffles(const Matrix& M,
                         set<vector<long>>& seen,
                         vector<Matrix>& results) {
    int n = (int)M.size();
    vector<int> idx(n);
    iota(idx.begin(), idx.end(), 0);

    do {
        Matrix candidate(n, Row(n));
        for (int i = 0; i < n; ++i)
            for (int j = 0; j < n; ++j)
                candidate[i][j] = M[i][idx[j]];

        auto key = flatten(candidate);
        if (!seen.count(key)) {
            seen.insert(key);
            results.push_back(candidate);
        }
    } while (next_permutation(idx.begin(), idx.end()));
}

// ─────────────────────────────────────────────────────────────
// 3. Element shuffling – all combinations of per-row element
//    permutations (each row's values shuffled independently)
// ─────────────────────────────────────────────────────────────
void generateElementShuffles(const Matrix& M,
                              set<vector<long>>& seen,
                              vector<Matrix>& results) {
    int n = (int)M.size();

    Matrix candidate(n, Row(n));

    function<void(int)> dfs = [&](int row) {
        if (row == n) {
            auto key = flatten(candidate);
            if (!seen.count(key)) {
                seen.insert(key);
                results.push_back(candidate);
            }
            return;
        }

        vector<int> idx(n);
        iota(idx.begin(), idx.end(), 0);
        do {
            for (int j = 0; j < n; ++j)
                candidate[row][j] = M[row][idx[j]];
            dfs(row + 1);
        } while (next_permutation(idx.begin(), idx.end()));
    };

    dfs(0);
}

// ─────────────────────────────────────────────────────────────
// Master generator – iteratively applies all three shuffle
// types to every discovered matrix until the set stabilises.
// ─────────────────────────────────────────────────────────────
vector<Matrix> generateAllPatternMatrices(const Matrix& seed) {
    set<vector<long>> seen;
    vector<Matrix>    results;

    seen.insert(flatten(seed));
    results.push_back(seed);

    size_t processed = 0;
    while (processed < results.size()) {
        Matrix cur = results[processed++];
        generateRowShuffles    (cur, seen, results);
        generateColShuffles    (cur, seen, results);
        generateElementShuffles(cur, seen, results);
    }

    return results;
}

// ─────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────
int main() {

    cout << "========================================\n";
    cout << "     Pattern Matrix Generator (NTL)\n";
    cout << "========================================\n\n";

    // ── Step 1: Input prime p ─────────────────────────────────
    long p;
    while (true) {
        cout << "Enter a prime number p: ";
        if (!(cin >> p)) {
            cin.clear(); cin.ignore(10000, '\n');
            cerr << "  [Error] Invalid input. Please enter an integer.\n";
            continue;
        }
        if (!isPrime(p)) {
            cerr << "  [Error] " << p << " is not prime. Please try again.\n";
            continue;
        }
        break;
    }
    cout << "  p = " << p << "  |  Row sum target (p-1) = " << p - 1 << "\n\n";

    // ── Step 2: Input matrix size n ───────────────────────────
    int n;
    while (true) {
        cout << "Enter matrix size n (matrix will be n x n): ";
        if (!(cin >> n) || n <= 0) {
            cin.clear(); cin.ignore(10000, '\n');
            cerr << "  [Error] Invalid input. Enter a positive integer.\n";
            continue;
        }
        // Need n² distinct values from {1 .. p-1}
        if ((long)(n * n) > p - 1) {
            cerr << "  [Error] Cannot build a " << n << "x" << n
                 << " globally-unique matrix with p=" << p << ".\n"
                 << "          Need " << (long)(n * n) << " distinct values but "
                 << "{1.." << p - 1 << "} has only " << p - 1 << ".\n";
            continue;
        }
        // Row sum p-1 must be achievable with n distinct positive integers
        long minRowSum = (long)n * (n + 1) / 2;  // 1+2+...+n
        if (minRowSum > p - 1) {
            cerr << "  [Error] p-1=" << p - 1
                 << " is too small to be a row sum of "
                 << n << " distinct positive integers "
                 << "(minimum possible sum = " << minRowSum << ").\n";
            continue;
        }
        break;
    }
    cout << "  Matrix size: " << n << " x " << n << "\n\n";

    // ── Step 3: Input seed pattern matrix ─────────────────────
    cout << "Enter the " << n << "x" << n << " seed pattern matrix row by row.\n";
    cout << "  Rules:\n";
    cout << "    * All elements must be in [1, " << p - 1 << "]\n";
    cout << "    * All elements must be globally unique (no repeats)\n";
    cout << "    * Each row must sum to " << p - 1 << "\n\n";

    Matrix seed(n, Row(n));

    while (true) {
        for (int i = 0; i < n; ++i) {
            cout << "  Row " << i + 1 << " [enter " << n << " values]: ";
            for (int j = 0; j < n; ++j)
                cin >> seed[i][j];
        }

        cout << "\nYou entered:\n";
        writeMatrix(cout, seed);

        if (isPatternMatrix(seed, p)) {
            cout << "  [OK] Seed matrix is valid!\n";
            break;
        } else {
            cerr << "  Please re-enter the matrix.\n\n";
        }
    }

    // ── Step 4: Generate all pattern matrices ─────────────────
    cout << "\nGenerating all pattern matrices via row / column / element shuffles...\n";
    vector<Matrix> results = generateAllPatternMatrices(seed);
    cout << "Done!  Total unique matrices found: " << results.size() << "\n";

    // ── Step 5: Write everything to pattern_output_demo_1.txt ────────
    const string outputFile = "pattern_output_demo_1.txt";
    ofstream out(outputFile);
    if (!out) {
        cerr << "[Error] Could not open \"" << outputFile << "\" for writing.\n";
        return 1;
    }

    // Header
    out << "============================================================\n";
    out << "             Pattern Matrix Generator - Output\n";
    out << "============================================================\n";
    out << "Prime p          : " << p              << "\n";
    out << "Matrix size      : " << n << " x " << n << "\n";
    out << "Row sum  (p-1)   : " << p - 1          << "\n";
    out << "Total matrices   : " << results.size() << "\n";
    out << "Shuffle types    : (1) Row  (2) Column  (3) Element\n";
    out << "============================================================\n\n";

    // Seed
    out << "Seed Matrix (user-provided):\n";
    writeMatrix(out, seed);

    out << "------------------------------------------------------------\n";
    out << "All Generated Pattern Matrices (no duplicates):\n";
    out << "------------------------------------------------------------\n\n";

    // All matrices numbered — print only the mod-p reduced matrix
    for (size_t i = 0; i < results.size(); ++i) {
        out << "Matrix #" << i + 1 << " (mod " << p << "):\n";
        Matrix modded = modMatrix(results[i], p);
        writeMatrix(out, modded);
    }

    out.close();

    cout << "\nAll " << results.size() << " matrices have been written to: "
         << outputFile << "\n";

    return 0;
}